name: Gradle Precommit

on:
  pull_request:
    branches:
      - '*'

jobs:
  test:
    name: gradle check

    runs-on: ubuntu-latest
    timeout-minutes: 15

    steps:
    - name: Checkout code
      uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

    - uses: ./.github/actions/prepare-for-build

    - name: Run gradle check (without tests)
      run: ./gradlew check -x test -Ptask.times=true --continue
